name: Build

on:
  push:
    branches:
      - feature/github-actions

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache Docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: shijima-wii-dev.tar.gz
          key: ${{ runner.os }}-dev-docker
      - name: Build Docker image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          pushd docker
          docker build -t shijima-wii-dev .
          docker save shijima-wii-dev | gzip > ../shijima-wii-dev.tar.gz
          popd
      - name: Import Docker image
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: |
          gunzip -c < shijima-wii-dev.tar.gz | docker load
      - name: Build debug
        run: |
          docker run --user $(id -u):$(id -g) --rm -v "$(pwd)":/work shijima-wii-dev bash -c \
            'rm -rf build && ./build.sh'
      - name: Archive debug
        uses: actions/upload-artifact@v4
        with:
          name: Shijima-Wii-debug
          path: |
            build/Shijima-Wii.dol
            build/Shijima-Wii.elf
      - name: Build debug
        run: |
          docker run --user $(id -u):$(id -g) --rm -v "$(pwd)":/work shijima-wii-dev bash -c \
            'rm -rf build-release && ./build-release.sh'
      - name: Archive release
        uses: actions/upload-artifact@v4
        with:
          name: Shijima-Wii-release
          path: |
            build-release/Shijima-Wii.dol
            build-release/Shijima-Wii.elf
